---
# This playbook prints a simple debug message
- name: Echo Hello, Fred and Wilma
  hosts: localhost
  vars:
    - pb_var1a : "test"
    - pb_var1b : ""
  tasks:
  - name: "playbook1 - testing input vars"
  - debug: msg="Hello, {{ pb_var1a }} and {{ pb_var1b }}"

