- name: Hello World Sample
  hosts: localhost
  vars:
  - var1 : "test"

  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! '{{ var1 }}'"
        
    - pause:
        minutes: 2
        
    - name: Hello Message
      debug:
        msg: "Final Message '{{ var1 }}'"
        
        
