---
- name: Install Package
  hosts: localhost
  vars:
    package: "date"

  tasks:
  - name: Install package
    command: "{{ package }}"
    register: cmdoutput
  - debug: msg="{{cmdoutput.stdout}}"
